In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import gc
import glob

# 그래프 기본 테마 설정
# https://coldbrown.co.kr/2023/07/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%8B%A4%EC%A0%84%ED%8E%B8-08-seaborn-sns-set%EC%9D%84-%ED%86%B5%ED%95%B4-%EC%8A%A4%ED%83%80%EC%9D%BC-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0/
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False


# 복잡한 통계 처리를 위한 라이브러리
from scipy import stats

In [2]:
# data_type = "train"
# month = "07"
# category = "잔액정보"

# local
root_path = '../../data'

# colab
# root_path = '/content/drive/MyDrive/12조 파이널프로젝트/data'

#drive_folder = f'{root_path}/스탯티즈_Raw_data/'

In [3]:
df1 = pd.read_csv(f'{root_path}/KBO FA 투수 [2013-2024]_최종_전처리+파생2.csv', encoding='utf-8')

- 15 윤석민 (fa 1년차)+ 계약 규모
- 15 송은범 (fa 1년차)
- 노경은 1차 fa 계약규모+ 2차 fa 관련 기록 
- 22 양현종 (fa 1년차)+ 계약 규모

### 1. 15 윤석민 (fa 1년차) + 계약규모

In [6]:
len(df1)

365

In [7]:
df2 = df1.copy()

In [8]:
df2.loc[193, ['FA 계약 연수', 'FA 계약 총액']] = [4, 900000]

In [9]:
new_row = {'FA년도': 2016, 
           '구단명':'KIA',
          '선수명': '윤석민',
          '세부 포지션': 'CP',
          '투':'우투',
          '구분':'FA 1년차',
          'FA등급':'A',
          '플레이년도':2015,
          '나이': 29,
          '게임수':51,
          '선발등판':0,
          '구원등판':51,
          '승리':2,
          '패전':6,
          '세이브':30,
          '블론세이브': 8,
          '홀드':0,
          '블론홀드':0,
          '이닝수':70,
          '자책점':23,
          '피안타':69,
          '2루타허용':11,
          '3루타허용':4,
          '피홈런':4,
          '볼넷허용':24,
          '사구허용':2,
          '탈삼진':68,
          '폭투':1,
          'ERA':2.96,
          'FIP':3.23,
          '선발 이닝':0,
          '구원 이닝':70,
          '선발 WAR':0,
          '구원 WAR':2.26,
          '종합 WAR':2.26,
          '연봉':125000,
          '비고1':'고졸',
          '잔류 여부':'잔류',
          'FA 계약 연수':0,
          'FA 계약 총액':0,
          '사사구':24,
          '완투':0,
          '완봉':0,
          '투구수':1146,
          '피장타율':0.385,
          '원클럽맨여부':1,
          '득점파크팩터':1011,
          '홈런파크팩터':1019,
          '장타파크팩터':1006,
          '국대출전횟수':5,
          '구종1':'포심',
          '구종2':'슬라',
          '구종1 구종가치':10,}

# 삽입할 위치 (예: 인덱스 2번 자리에 추가)
insert_at = 194

# 위/아래로 나눠서 concat
df_top = df2.iloc[:insert_at]
df_bottom = df2.iloc[insert_at:]

# 새 행을 데이터프레임으로 만들어서 붙임
df2 = pd.concat([df_top, pd.DataFrame([new_row]), df_bottom], ignore_index=True)

### 2. 15 송은범 (fa 1년차)

In [11]:
new_row = {'FA년도': 2016, 
           '구단명':'한화',
          '선수명': '송은범',
          '세부 포지션': 'RP',
          '투':'우투',
          '구분':'FA 1년차',
          'FA등급':'A',
          '플레이년도':2015,
          '나이': 31,
          '게임수':33,
          '선발등판':14,
          '구원등판':19,
          '승리':2,
          '패전':9,
          '세이브':4,
          '블론세이브': 1,
          '홀드':1,
          '블론홀드':0,
          '이닝수':70.1,
          '자책점':55,
          '피안타':103,
          '2루타허용':22,
          '3루타허용':2,
          '피홈런':10,
          '볼넷허용':30,
          '사구허용':4,
          '탈삼진':48,
          '폭투':11,
          'ERA':7.04,
          'FIP':5.58,
          '선발 이닝':47,
          '구원 이닝':23.1,
          '선발 WAR':-0.44,
          '구원 WAR':0.48,
          '종합 WAR':0.04,
          '연봉':45000,
          '비고1':'고졸',
          '잔류 여부':'이적',
          'FA 계약 연수':0,
          'FA 계약 총액':0,
          '사사구':34,
          '완투':0,
          '완봉':0,
          '투구수':1318,
          '피장타율':0.530,
          '원클럽맨여부':0,
          '득점파크팩터':1015,
          '홈런파크팩터':1002,
          '장타파크팩터':997,
          '국대출전횟수':1,
          '구종1':'포심',
          '구종2':'슬라',
          '구종1 구종가치':-1.3,}

# 삽입할 위치 (예: 인덱스 2번 자리에 추가)
insert_at = 114

# 위/아래로 나눠서 concat
df_top = df2.iloc[:insert_at]
df_bottom = df2.iloc[insert_at:]

# 새 행을 데이터프레임으로 만들어서 붙임
df2 = pd.concat([df_top, pd.DataFrame([new_row]), df_bottom], ignore_index=True)

### 3. 노경은 1차 fa 계약규모 + fa 1년차 추가

In [13]:
new_row = {'FA년도': 2021, 
           '구단명':'롯데',
          '선수명': '노경은',
          '세부 포지션': 'SP',
          '투':'우투',
          '구분':'FA 1년차',
          'FA등급':'A',
          '플레이년도':2020,
          '나이': 36,
          '게임수':25,
          '선발등판':24,
          '구원등판':1,
          '승리':5,
          '패전':10,
          '세이브':0,
          '블론세이브': 0,
          '홀드':0,
          '블론홀드':0,
          '이닝수':133,
          '자책점':72,
          '피안타':139,
          '2루타허용':31,
          '3루타허용':1,
          '피홈런':19,
          '볼넷허용':40,
          '사구허용':3,
          '탈삼진':77,
          '폭투':3,
          'ERA':4.87,
          'FIP':5.20,
          '선발 이닝':131.2,
          '구원 이닝':1.1,
          '선발 WAR':3.20,
          '구원 WAR':-0.27,
          '종합 WAR':2.93,
          '연봉':20000,
          '비고1':'고졸',
          '잔류 여부':'잔류',
          'FA 계약 연수':2,
          'FA 계약 총액':110000,
          '사사구':43,
          '완투':1,
          '완봉':0,
          '투구수':2138,
          '피장타율':0.440,
          '원클럽맨여부':0,
          '득점파크팩터':1043,
          '홈런파크팩터':1047,
          '장타파크팩터':1062,
          '국대출전횟수':1,
          '구종1':'슬라',
          '구종2':'첸접',
          '구종1 구종가치':8.3}
    
    


# 삽입할 위치 (예: 인덱스 2번 자리에 추가)
insert_at = 67

# 위/아래로 나눠서 concat
df_top = df2.iloc[:insert_at]
df_bottom = df2.iloc[insert_at:]


df2 = pd.concat([df_top, pd.DataFrame([new_row]), df_bottom], ignore_index=True)

### 4. 22 양현종 (fa 1년차) + 계약 규모

In [15]:
new_row = {'FA년도': 2023, 
           '구단명':'KIA',
          '선수명': '양현종',
          '세부 포지션': 'SP',
          '투':'좌투',
          '구분':'FA 1년차',
          'FA등급':'B',
          '플레이년도':2022,
          '나이': 34,
          '게임수':30,
          '선발등판':30,
          '구원등판':0,
          '승리':12,
          '패전':7,
          '세이브':0,
          '블론세이브': 0,
          '홀드':0,
          '블론홀드':0,
          '이닝수':175.1,
          '자책점':75,
          '피안타':170,
          '2루타허용':33,
          '3루타허용':3,
          '피홈런':14,
          '볼넷허용':50,
          '사구허용':3,
          '탈삼진':141,
          '폭투':3,
          'ERA':3.85,
          'FIP':3.66,
          '선발 이닝':175.1,
          '구원 이닝':0,
          '선발 WAR':3.46,
          '구원 WAR':0,
          '종합 WAR':3.46,
          '연봉':100000,
          '비고1':'고졸',
          '잔류 여부':'잔류',
          'FA 계약 연수':4,
          'FA 계약 총액':1070000,
          '사사구':53,
          '완투':0,
          '완봉':0,
          '투구수':2856,
          '피장타율':0.374,
          '원클럽맨여부':1,
          '득점파크팩터':989,
          '홈런파크팩터':1013,
          '장타파크팩터':1000,
          '국대출전횟수':6,
          '구종1':'포심',
          '구종2':'슬라',
          '구종1 구종가치':4.7}
    
    


# 삽입할 위치 (예: 인덱스 2번 자리에 추가)
insert_at = 145

# 위/아래로 나눠서 concat
df_top = df2.iloc[:insert_at]
df_bottom = df2.iloc[insert_at:]


df2= pd.concat([df_top, pd.DataFrame([new_row]), df_bottom], ignore_index=True)

In [16]:
df2 = df2.sort_values(by=['선수명', 'FA년도']).reset_index(drop=True)

In [17]:
# '강윤구' 선수의 행 제거
df2 = df2[df2['선수명'] != '강윤구'].reset_index(drop=True)

In [18]:
# df2.to_csv('../../data/KBO FA 투수 [2013-2024]_최종_전처리_ver03.csv', index = False, encoding='utf-8-sig')

In [19]:
df2

,FA년도,구단명,선수명,세부 포지션,투,구분,FA등급,플레이년도,나이,게임수,...,투구수,피장타율,원클럽맨여부,득점파크팩터,홈런파크팩터,장타파크팩터,국대출전횟수,구종1,구종2,구종1 구종가치
0,2011,롯데,강영식,RP,좌투,자격유지,A,2010,29.0,63.0,...,907,0.412,0.0,1032.0,1128.0,1093.0,0,NaN,NaN,NaN
1,2012,롯데,강영식,RP,좌투,자격유지,A,2011,30.0,64.0,...,731,0.360,0.0,1044.0,1128.0,1093.0,0,NaN,NaN,NaN
2,2013,롯데,강영식,RP,좌투,자격유지,A,2012,31.0,55.0,...,757,0.340,0.0,1033.0,1128.0,1093.0,0,NaN,NaN,NaN
3,2014,롯데,강영식,RP,좌투,자격유지,A,2013,32.0,55.0,...,675,0.298,0.0,1058.0,1128.0,1093.0,0,포심,슬라,5.0
4,2015,롯데,강영식,RP,좌투,FA 1년차,A,2014,33.0,52.0,...,813,0.393,0.0,1045.0,1102.0,1062.0,0,포심,슬라,-5.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2021,두산,홍건희,RP,우투,신규,A,2020,28.0,60.0,...,1210,0.440,0.0,939.0,847.0,949.0,0,포심,슬라,8.0
361,2022,두산,홍건희,RP,우투,신규,A,2021,29.0,65.0,...,1272,0.313,0.0,944.0,840.0,949.0,0,포심,슬라,16.6
362,2023,두산,홍건희,CP,우투,신규,A,2022,30.0,58.0,...,1009,0.353,0.0,953.0,867.0,961.0,0,포심,슬라,7.0
363,2024,두산,홍건희,CP,우투,신규,A,2023,31.0,64.0,...,1092,0.386,0.0,959.0,857.0,976.0,0,포심,슬라,-2.2
364,2025,두산,홍건희,CP,우투,FA 1년차,A,2024,32.0,65.0,...,1034,0.359,0.0,969.0,897.0,985.0,0,포심,슬라,7.1

In [20]:
df100 = pd.read_csv(f'{root_path}/KBO FA 투수 [2013-2024]_최종_전처리_ver03.csv', encoding='utf-8')
df100

,FA년도,구단명,선수명,세부 포지션,투,구분,FA등급,플레이년도,나이,게임수,...,투구수,피장타율,원클럽맨여부,득점파크팩터,홈런파크팩터,장타파크팩터,국대출전횟수,구종1,구종2,구종1 구종가치
0,2011,롯데,강영식,RP,좌투,자격유지,A,2010,29.0,63.0,...,907,0.412,0.0,1032.0,1128.0,1093.0,0,NaN,NaN,NaN
1,2012,롯데,강영식,RP,좌투,자격유지,A,2011,30.0,64.0,...,731,0.360,0.0,1044.0,1128.0,1093.0,0,NaN,NaN,NaN
2,2013,롯데,강영식,RP,좌투,자격유지,A,2012,31.0,55.0,...,757,0.340,0.0,1033.0,1128.0,1093.0,0,NaN,NaN,NaN
3,2014,롯데,강영식,RP,좌투,자격유지,A,2013,32.0,55.0,...,675,0.298,0.0,1058.0,1128.0,1093.0,0,포심,슬라,5.0
4,2015,롯데,강영식,RP,좌투,FA 1년차,A,2014,33.0,52.0,...,813,0.393,0.0,1045.0,1102.0,1062.0,0,포심,슬라,-5.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2021,두산,홍건희,RP,우투,신규,A,2020,28.0,60.0,...,1210,0.440,0.0,939.0,847.0,949.0,0,포심,슬라,8.0
361,2022,두산,홍건희,RP,우투,신규,A,2021,29.0,65.0,...,1272,0.313,0.0,944.0,840.0,949.0,0,포심,슬라,16.6
362,2023,두산,홍건희,CP,우투,신규,A,2022,30.0,58.0,...,1009,0.353,0.0,953.0,867.0,961.0,0,포심,슬라,7.0
363,2024,두산,홍건희,CP,우투,신규,A,2023,31.0,64.0,...,1092,0.386,0.0,959.0,857.0,976.0,0,포심,슬라,-2.2
364,2025,두산,홍건희,CP,우투,FA 1년차,A,2024,32.0,65.0,...,1034,0.359,0.0,969.0,897.0,985.0,0,포심,슬라,7.1

In [ ]:
df300 = pd.read_csv(f'{root_path}/KBO FA 투수 [2013-2024]_최종_전처리_ver03.csv', encoding='utf-8')

In [21]:
df200 = pd.read_excel(f'{root_path}/WHIP_추가.xlsx')
df200

     선수명  플레이년도  WHIP
0    강영식   2010  1.41
1    강영식   2011  1.39
2    강영식   2012  1.44
3    강영식   2013  1.29
4    강영식   2014  1.49
..   ...    ...   ...
359  홍건희   2020  1.40
360  홍건희   2021  1.24
361  홍건희   2022  1.27
362  홍건희   2023  1.48
363  홍건희   2024  1.48

[364 rows x 3 columns]

In [22]:
# 3. 데이터 전처리 (공백 제거 및 타입 통일)
df100['선수명'] = df100['선수명'].astype(str).str.strip()
df200['선수명'] = df200['선수명'].astype(str).str.strip()
df100['플레이년도'] = df100['플레이년도'].astype(int)
df200['플레이년도'] = df200['플레이년도'].astype(int)

In [23]:
# 4. 병합 (left join)
df100_merged = df100.merge(df200, on=['선수명', '플레이년도'], how='left')

In [24]:
# 5. 저장
# df100_merged.to_csv(f'{root_path}/KBO FA 투수 [2013-2024]_최종_전처리_ver04.csv', index=False, encoding='utf-8-sig')