In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import gc
import glob

# 그래프 기본 테마 설정
# https://coldbrown.co.kr/2023/07/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%8B%A4%EC%A0%84%ED%8E%B8-08-seaborn-sns-set%EC%9D%84-%ED%86%B5%ED%95%B4-%EC%8A%A4%ED%83%80%EC%9D%BC-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0/
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False


# 복잡한 통계 처리를 위한 라이브러리
from scipy import stats

In [2]:
# data_type = "train"
# month = "07"
# category = "잔액정보"

# local
root_path = '../../data'

# colab
# root_path = '/content/drive/MyDrive/12조 파이널프로젝트/data'

#drive_folder = f'{root_path}/스탯티즈_Raw_data/'

In [5]:
df1 = pd.read_csv(f'{root_path}/투수_데이터_최종.csv', encoding='utf-8')

,FA년도,구단명,선수명,세부 포지션,투,구분,FA등급,플레이년도,나이,게임수,...,득점파크팩터,홈런파크팩터,장타파크팩터,국대출전횟수,구종1,구종2,구종1 구종가치,WHIP,AAV,n차
0,2011,롯데,강영식(1차),RP,좌투,자격유지,A,2010,29,63,...,1032.0,1128.0,1093.0,0,NaN,NaN,NaN,1.41,42500.000000,0
1,2012,롯데,강영식(1차),RP,좌투,자격유지,A,2011,30,64,...,1044.0,1128.0,1093.0,0,NaN,NaN,NaN,1.39,42500.000000,0
2,2013,롯데,강영식(1차),RP,좌투,자격유지,A,2012,31,55,...,1033.0,1128.0,1093.0,0,NaN,NaN,NaN,1.44,42500.000000,0
3,2014,롯데,강영식(1차),RP,좌투,자격유지,A,2013,32,55,...,1058.0,1128.0,1093.0,0,포심,슬라,5.0,1.29,42500.000000,0
4,2015,롯데,강영식(1차),RP,좌투,FA 1년차,A,2014,33,52,...,1045.0,1102.0,1062.0,0,포심,슬라,-5.6,1.49,42500.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,2019,NC,구창모,SP,좌투,다년계약,다년계약,2018,21,36,...,1004.0,1093.0,992.0,1,포심,커브,2.3,1.58,208333.333333,0
339,2020,NC,구창모,SP,좌투,다년계약,다년계약,2019,22,23,...,1043.0,1084.0,1018.0,1,포심,슬라,17.8,1.18,208333.333333,0
340,2021,NC,구창모,SP,좌투,다년계약,다년계약,2020,23,15,...,1037.0,1091.0,1026.0,1,포심,슬라,21.9,0.81,208333.333333,0
341,2023,NC,구창모,SP,좌투,다년계약,다년계약,2022,25,19,...,1013.0,1095.0,1026.0,1,포심,슬라,23.4,1.08,208333.333333,0
342,2024,NC,구창모,SP,좌투,FA 1년차,다년계약,2023,26,11,...,1005.0,1094.0,1029.0,1,포심,슬라,10.9,1.05,208333.333333,0