In [171]:
import pandas as pd

In [173]:
df = pd.read_csv('FA_야수_데이터_합치기.csv')

In [175]:
df.isna().sum()

FA년도          0
구단명           0
선수명           0
포지션          13
투             0
             ..
TEAM oWAR    67
TEAM dWAR    67
TEAM 연봉      67
PA_y         13
wRC+         13
Length: 62, dtype: int64

In [177]:
pd.set_option('display.max_columns', None)
pd.reset_option('display.max_rows', None)

In [179]:
df = df[~df['구단명'].isin(['군 복무', '은퇴', '구단 징계', '부상 시즌 아웃'])]

In [181]:
df = df.reset_index()

In [183]:
df

,index,FA년도,구단명,선수명,포지션,투,타,인정년수,구분,FA등급,플레이년도,Age,G,PA_x,AB,R,H,2B,3B,HP,HR,RBI,SB,CS,BB,SO,GDP,SF,수비_필딩 RAA,수비_포지션 RAA,전체수비 RAA,oWAR,dWAR,연봉,비고,잔류 여부,FA 계약 연수,FA 계약 총액,TEAM RANK,TEAM G,TEAM PA,TEAM AB,TEAM R,TEAM H,TEAM 2B,TEAM 3B,TEAM HP,TEAM HR,TEAM RBI,TEAM SB,TEAM CS,TEAM BB,TEAM SO,TEAM GDP,TEAM SF,TEAM 수비_필딩 RAA,TEAM 수비_포지션 RAA,TEAM 전체수비 RAA,TEAM oWAR,TEAM dWAR,TEAM 연봉,PA_y,wRC+
0,0,2011,롯데,강민호,C,우투,우타,9.0,신규,A,2010,25.0,117.0,465.0,410.0,66.0,125.0,19.0,1.0,8.0,23.0,72.0,2.0,7.0,42.0,65.0,16.0,5.0,1.74,9.48,11.21,3.67,0.35,NaN,고졸,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,465.0,134.4
1,1,2012,롯데,강민호,C,우투,우타,9.0,신규,A,2011,26.0,124.0,506.0,450.0,63.0,130.0,25.0,2.0,8.0,19.0,66.0,4.0,6.0,47.0,81.0,18.0,1.0,-1.00,11.72,10.73,3.90,0.23,NaN,고졸,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,506.0,130.3
2,2,2013,롯데,강민호,C,우투,우타,9.0,신규,A,2012,27.0,119.0,454.0,400.0,41.0,109.0,21.0,0.0,8.0,19.0,66.0,0.0,1.0,44.0,97.0,9.0,2.0,-1.68,9.16,7.48,3.76,0.65,NaN,고졸,NaN,NaN,NaN,4.0,133.0,5043.0,4481.0,509.0,1179.0,202.0,16.0,54.0,73.0,479.0,119.0,53.0,375.0,890.0,91.0,26.0,-41.49,13.36,-35.33,21.15,-3.15,289700.0,454.0,132.9
3,3,2014,롯데,강민호,C,우투,우타,9.0,신규,A,2013,28.0,105.0,405.0,327.0,48.0,77.0,13.0,0.0,11.0,11.0,57.0,4.0,1.0,60.0,87.0,5.0,6.0,7.18,8.93,16.11,1.75,1.81,NaN,고졸,잔류,4.0,75.0,5.0,128.0,4978.0,4289.0,556.0,1118.0,208.0,18.0,71.0,61.0,522.0,133.0,58.0,503.0,862.0,92.0,41.0,17.08,1.43,18.51,15.17,2.53,311900.0,405.0,99.2
4,4,2015,롯데,강민호,C,우투,우타,4.0,FA 1년차,A,2014,29.0,98.0,360.0,310.0,37.0,71.0,14.0,2.0,13.0,16.0,40.0,1.0,2.0,33.0,92.0,6.0,4.0,4.54,8.09,12.63,1.20,0.40,100000.0,고졸,NaN,NaN,NaN,7.0,128.0,5194.0,4487.0,716.0,1288.0,252.0,26.0,70.0,121.0,685.0,63.0,41.0,534.0,964.0,95.0,41.0,1.14,15.71,-6.57,16.88,0.10,510600.0,360.0,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,646,2019,KT,황재균,3B,우투,우타,4.0,재자격,B,2018,31.0,142.0,588.0,530.0,76.0,157.0,41.0,3.0,4.0,25.0,88.0,14.0,7.0,49.0,120.0,5.0,3.0,-0.96,-1.50,-2.46,3.54,-0.09,120000.0,고졸,NaN,NaN,NaN,9.0,144.0,5605.0,5026.0,757.0,1382.0,264.0,13.0,46.0,206.0,721.0,80.0,57.0,464.0,1109.0,103.0,26.0,-2.41,-7.35,-12.03,16.22,-0.35,607700.0,588.0,117.0
633,647,2020,KT,황재균,3B,우투,우타,4.0,재자격,B,2019,32.0,124.0,507.0,448.0,78.0,127.0,16.0,3.0,2.0,20.0,67.0,10.0,7.0,52.0,71.0,10.0,5.0,8.99,0.31,9.31,3.80,0.92,120000.0,고졸,NaN,NaN,NaN,6.0,144.0,5582.0,4965.0,650.0,1375.0,187.0,20.0,52.0,103.0,615.0,104.0,44.0,475.0,975.0,113.0,45.0,36.35,39.04,26.31,21.52,3.72,514900.0,507.0,127.0
634,648,2021,KT,황재균,3B,우투,우타,4.0,재자격,B,2020,33.0,134.0,600.0,541.0,108.0,169.0,35.0,5.0,5.0,21.0,97.0,11.0,6.0,47.0,98.0,12.0,4.0,5.03,-0.10,4.93,4.72,0.47,120000.0,고졸,NaN,NaN,NaN,3.0,144.0,5762.0,5047.0,813.0,1432.0,238.0,21.0,52.0,163.0,767.0,106.0,50.0,554.0,1097.0,104.0,45.0,21.71,15.80,11.90,27.89,2.10,584000.0,600.0,129.5
635,649,2022,KT,황재균,3B,우투,우타,4.0,재자격,B,2021,34.0,117.0,507.0,453.0,74.0,132.0,16.0,2.0,3.0,10.0,56.0,11.0,4.0,46.0,92.0,11.0,4.0,4.16,-0.12,4.04,2.41,0.41,80000.0,고졸,잔류,4.0,60.0,1.0,144.0,5627.0,4810.0,719.0,1276.0,219.0,11.0,58.0,106.0,673.0,112.0,46.0,645.0,1047.0,105.0,44.0,10.21,-7.11,0.42,21.86,1.33,575800.0,507.0,107.9
636,650,2023,KT,황재균,3B,우투,우타,NaN,FA 1년차,NaN,2022,35.0,141.0,581.0,519.0,59.0,136.0,25.0,3.0,5.0,10.0,64.0,6.0,3.0,53.0,99.0,17.0,2.0,-2.49,-0.25,-2.74,2.07,-0.26,40000.0,NaN,NaN,NaN,NaN,4.0,144.0,5547.0,4864.0,631.0,1237.0,192.0,19.0,49.0,119.0,588.0,89.0,34.0,519.0,1183.0,105.0,44.0,13.16,14.83,4.34,17.82,1.35,749000.0,581.0,97.1

In [185]:
df.columns

Index(['index', 'FA년도', '구단명', '선수명', '포지션', '투', '타', '인정년수', '구분', 'FA등급',
       '플레이년도', 'Age', 'G', 'PA_x', 'AB', 'R', 'H', '2B', '3B', 'HP', 'HR',
       'RBI', 'SB', 'CS', 'BB', 'SO', 'GDP', 'SF', '수비_필딩 RAA', '수비_포지션 RAA',
       '전체수비 RAA', 'oWAR', 'dWAR', '연봉', '비고', '잔류 여부', 'FA 계약 연수', 'FA 계약 총액',
       'TEAM RANK', 'TEAM G', 'TEAM PA', 'TEAM AB', 'TEAM R', 'TEAM H',
       'TEAM 2B', 'TEAM 3B', 'TEAM HP', 'TEAM HR', 'TEAM RBI', 'TEAM SB',
       'TEAM CS', 'TEAM BB', 'TEAM SO', 'TEAM GDP', 'TEAM SF',
       'TEAM 수비_필딩 RAA', 'TEAM 수비_포지션 RAA', 'TEAM 전체수비 RAA', 'TEAM oWAR',
       'TEAM dWAR', 'TEAM 연봉', 'PA_y', 'wRC+'],
      dtype='object')

In [191]:
df = df.drop(['index'],axis=1)

In [193]:
df.columns = ['FA년도', '구단명', '선수명', '포지션', '투', '타', '인정년수', '구분', 'FA등급', '플레이년도',
       '나이', '게임수', '타석수', '타수', '득점', '안타', '2루타', '3루타', '사구', '홈런', '타점', '도루성공',
       '도루실패', '볼넷', '삼진', '병살타', '희생플라이', '평균대비수비득점기여', '수비_포지션 RAA', '전체수비 RAA',
       '공격WAR', '수비WAR', '연봉', '비고', '잔류 여부', 'FA 계약 연수', 'FA 계약 총액',
       'TEAM 순위', 'TEAM 게임수', 'TEAM 타석수', 'TEAM 타수', 'TEAM 득점', 'TEAM 안타',
       'TEAM 2루타', 'TEAM 3루타', 'TEAM 사구', 'TEAM 홈런', 'TEAM 타점', 'TEAM 도루',
       'TEAM 도루실패', 'TEAM 볼넷', 'TEAM 삼진', 'TEAM 병살타', 'TEAM 희생플라이',
       'TEAM 평균대비수비득점기여', 'TEAM 수비_포지션 RAA', 'TEAM 전체수비 RAA', 'TEAM 공격WAR',
       'TEAM 수비WAR', 'TEAM 연봉', '타석수y', 'wRC+']

In [137]:
df

,FA년도,구단명,선수명,포지션,투,타,인정년수,구분,FA등급,플레이년도,나이,게임수,타석수,타수,득점,안타,2루타,3루타,사구,홈런,타점,도루성공,도루실패,볼넷,삼진,병살타,희생플라이,평균대비수비득점기여,수비_포지션 RAA,전체수비 RAA,공격WAR,수비WAR,연봉,비고,잔류 여부,FA 계약 연수,FA 계약 총액,TEAM 순위,TEAM 게임수,TEAM 타석수,TEAM 타수,TEAM 득점,TEAM 안타,TEAM 2루타,TEAM 3루타,TEAM 사구,TEAM 홈런,TEAM 타점,TEAM 도루,TEAM 도루실패,TEAM 볼넷,TEAM 삼진,TEAM 병살타,TEAM 희생플라이,TEAM 평균대비수비득점기여,TEAM 수비_포지션 RAA,TEAM 전체수비 RAA,TEAM 공격WAR,TEAM 수비WAR,TEAM 연봉,타석수y,wRC+
0,2011,롯데,강민호,C,우투,우타,9.0,신규,A,2010,25.0,117.0,465.0,410.0,66.0,125.0,19.0,1.0,8.0,23.0,72.0,2.0,7.0,42.0,65.0,16.0,5.0,1.74,9.48,11.21,3.67,0.35,NaN,고졸,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,465.0,134.4
1,2012,롯데,강민호,C,우투,우타,9.0,신규,A,2011,26.0,124.0,506.0,450.0,63.0,130.0,25.0,2.0,8.0,19.0,66.0,4.0,6.0,47.0,81.0,18.0,1.0,-1.00,11.72,10.73,3.90,0.23,NaN,고졸,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,506.0,130.3
2,2013,롯데,강민호,C,우투,우타,9.0,신규,A,2012,27.0,119.0,454.0,400.0,41.0,109.0,21.0,0.0,8.0,19.0,66.0,0.0,1.0,44.0,97.0,9.0,2.0,-1.68,9.16,7.48,3.76,0.65,NaN,고졸,NaN,NaN,NaN,4.0,133.0,5043.0,4481.0,509.0,1179.0,202.0,16.0,54.0,73.0,479.0,119.0,53.0,375.0,890.0,91.0,26.0,-41.49,13.36,-35.33,21.15,-3.15,289700.0,454.0,132.9
3,2014,롯데,강민호,C,우투,우타,9.0,신규,A,2013,28.0,105.0,405.0,327.0,48.0,77.0,13.0,0.0,11.0,11.0,57.0,4.0,1.0,60.0,87.0,5.0,6.0,7.18,8.93,16.11,1.75,1.81,NaN,고졸,잔류,4.0,75.0,5.0,128.0,4978.0,4289.0,556.0,1118.0,208.0,18.0,71.0,61.0,522.0,133.0,58.0,503.0,862.0,92.0,41.0,17.08,1.43,18.51,15.17,2.53,311900.0,405.0,99.2
4,2015,롯데,강민호,C,우투,우타,4.0,FA 1년차,A,2014,29.0,98.0,360.0,310.0,37.0,71.0,14.0,2.0,13.0,16.0,40.0,1.0,2.0,33.0,92.0,6.0,4.0,4.54,8.09,12.63,1.20,0.40,100000.0,고졸,NaN,NaN,NaN,7.0,128.0,5194.0,4487.0,716.0,1288.0,252.0,26.0,70.0,121.0,685.0,63.0,41.0,534.0,964.0,95.0,41.0,1.14,15.71,-6.57,16.88,0.10,510600.0,360.0,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,2019,KT,황재균,3B,우투,우타,4.0,재자격,B,2018,31.0,142.0,588.0,530.0,76.0,157.0,41.0,3.0,4.0,25.0,88.0,14.0,7.0,49.0,120.0,5.0,3.0,-0.96,-1.50,-2.46,3.54,-0.09,120000.0,고졸,NaN,NaN,NaN,9.0,144.0,5605.0,5026.0,757.0,1382.0,264.0,13.0,46.0,206.0,721.0,80.0,57.0,464.0,1109.0,103.0,26.0,-2.41,-7.35,-12.03,16.22,-0.35,607700.0,588.0,117.0
633,2020,KT,황재균,3B,우투,우타,4.0,재자격,B,2019,32.0,124.0,507.0,448.0,78.0,127.0,16.0,3.0,2.0,20.0,67.0,10.0,7.0,52.0,71.0,10.0,5.0,8.99,0.31,9.31,3.80,0.92,120000.0,고졸,NaN,NaN,NaN,6.0,144.0,5582.0,4965.0,650.0,1375.0,187.0,20.0,52.0,103.0,615.0,104.0,44.0,475.0,975.0,113.0,45.0,36.35,39.04,26.31,21.52,3.72,514900.0,507.0,127.0
634,2021,KT,황재균,3B,우투,우타,4.0,재자격,B,2020,33.0,134.0,600.0,541.0,108.0,169.0,35.0,5.0,5.0,21.0,97.0,11.0,6.0,47.0,98.0,12.0,4.0,5.03,-0.10,4.93,4.72,0.47,120000.0,고졸,NaN,NaN,NaN,3.0,144.0,5762.0,5047.0,813.0,1432.0,238.0,21.0,52.0,163.0,767.0,106.0,50.0,554.0,1097.0,104.0,45.0,21.71,15.80,11.90,27.89,2.10,584000.0,600.0,129.5
635,2022,KT,황재균,3B,우투,우타,4.0,재자격,B,2021,34.0,117.0,507.0,453.0,74.0,132.0,16.0,2.0,3.0,10.0,56.0,11.0,4.0,46.0,92.0,11.0,4.0,4.16,-0.12,4.04,2.41,0.41,80000.0,고졸,잔류,4.0,60.0,1.0,144.0,5627.0,4810.0,719.0,1276.0,219.0,11.0,58.0,106.0,673.0,112.0,46.0,645.0,1047.0,105.0,44.0,10.21,-7.11,0.42,21.86,1.33,575800.0,507.0,107.9
636,2023,KT,황재균,3B,우투,우타,NaN,FA 1년차,NaN,2022,35.0,141.0,581.0,519.0,59.0,136.0,25.0,3.0,5.0,10.0,64.0,6.0,3.0,53.0,99.0,17.0,2.0,-2.49,-0.25,-2.74,2.07,-0.26,40000.0,NaN,NaN,NaN,NaN,4.0,144.0,5547.0,4864.0,631.0,1237.0,192.0,19.0,49.0,119.0,588.0,89.0,34.0,519.0,1183.0,105.0,44.0,13.16,14.83,4.34,17.82,1.35,749000.0,581.0,97.1

In [195]:
a1 = df[['선수명','플레이년도','타석수','타석수y']]
pa = a1[a1['타석수'] != a1['타석수y']]
pa

     선수명  플레이년도    타석수   타석수y
416  이우민   2013  251.0  453.0
417  이우민   2014  103.0  418.0
418  이우민   2015  174.0  585.0
419  이우민   2016   98.0  530.0
420  이우민   2017  215.0  200.0
543  조인성   2014  185.0   31.0
544  조인성   2014  185.0  154.0
567  최재훈   2018  420.0  341.0

In [197]:
df.loc[543, '타석수'] = 31.0
df.loc[544, '타석수'] = 154.0
df.loc[567, '타석수'] = 341.0

In [199]:
df= df.drop(['타석수y'], axis = 1)

df

,FA년도,구단명,선수명,포지션,투,타,인정년수,구분,FA등급,플레이년도,나이,게임수,타석수,타수,득점,안타,2루타,3루타,사구,홈런,타점,도루성공,도루실패,볼넷,삼진,병살타,희생플라이,평균대비수비득점기여,수비_포지션 RAA,전체수비 RAA,공격WAR,수비WAR,연봉,비고,잔류 여부,FA 계약 연수,FA 계약 총액,TEAM 순위,TEAM 게임수,TEAM 타석수,TEAM 타수,TEAM 득점,TEAM 안타,TEAM 2루타,TEAM 3루타,TEAM 사구,TEAM 홈런,TEAM 타점,TEAM 도루,TEAM 도루실패,TEAM 볼넷,TEAM 삼진,TEAM 병살타,TEAM 희생플라이,TEAM 평균대비수비득점기여,TEAM 수비_포지션 RAA,TEAM 전체수비 RAA,TEAM 공격WAR,TEAM 수비WAR,TEAM 연봉,wRC+
0,2011,롯데,강민호,C,우투,우타,9.0,신규,A,2010,25.0,117.0,465.0,410.0,66.0,125.0,19.0,1.0,8.0,23.0,72.0,2.0,7.0,42.0,65.0,16.0,5.0,1.74,9.48,11.21,3.67,0.35,NaN,고졸,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.4
1,2012,롯데,강민호,C,우투,우타,9.0,신규,A,2011,26.0,124.0,506.0,450.0,63.0,130.0,25.0,2.0,8.0,19.0,66.0,4.0,6.0,47.0,81.0,18.0,1.0,-1.00,11.72,10.73,3.90,0.23,NaN,고졸,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,130.3
2,2013,롯데,강민호,C,우투,우타,9.0,신규,A,2012,27.0,119.0,454.0,400.0,41.0,109.0,21.0,0.0,8.0,19.0,66.0,0.0,1.0,44.0,97.0,9.0,2.0,-1.68,9.16,7.48,3.76,0.65,NaN,고졸,NaN,NaN,NaN,4.0,133.0,5043.0,4481.0,509.0,1179.0,202.0,16.0,54.0,73.0,479.0,119.0,53.0,375.0,890.0,91.0,26.0,-41.49,13.36,-35.33,21.15,-3.15,289700.0,132.9
3,2014,롯데,강민호,C,우투,우타,9.0,신규,A,2013,28.0,105.0,405.0,327.0,48.0,77.0,13.0,0.0,11.0,11.0,57.0,4.0,1.0,60.0,87.0,5.0,6.0,7.18,8.93,16.11,1.75,1.81,NaN,고졸,잔류,4.0,75.0,5.0,128.0,4978.0,4289.0,556.0,1118.0,208.0,18.0,71.0,61.0,522.0,133.0,58.0,503.0,862.0,92.0,41.0,17.08,1.43,18.51,15.17,2.53,311900.0,99.2
4,2015,롯데,강민호,C,우투,우타,4.0,FA 1년차,A,2014,29.0,98.0,360.0,310.0,37.0,71.0,14.0,2.0,13.0,16.0,40.0,1.0,2.0,33.0,92.0,6.0,4.0,4.54,8.09,12.63,1.20,0.40,100000.0,고졸,NaN,NaN,NaN,7.0,128.0,5194.0,4487.0,716.0,1288.0,252.0,26.0,70.0,121.0,685.0,63.0,41.0,534.0,964.0,95.0,41.0,1.14,15.71,-6.57,16.88,0.10,510600.0,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,2019,KT,황재균,3B,우투,우타,4.0,재자격,B,2018,31.0,142.0,588.0,530.0,76.0,157.0,41.0,3.0,4.0,25.0,88.0,14.0,7.0,49.0,120.0,5.0,3.0,-0.96,-1.50,-2.46,3.54,-0.09,120000.0,고졸,NaN,NaN,NaN,9.0,144.0,5605.0,5026.0,757.0,1382.0,264.0,13.0,46.0,206.0,721.0,80.0,57.0,464.0,1109.0,103.0,26.0,-2.41,-7.35,-12.03,16.22,-0.35,607700.0,117.0
633,2020,KT,황재균,3B,우투,우타,4.0,재자격,B,2019,32.0,124.0,507.0,448.0,78.0,127.0,16.0,3.0,2.0,20.0,67.0,10.0,7.0,52.0,71.0,10.0,5.0,8.99,0.31,9.31,3.80,0.92,120000.0,고졸,NaN,NaN,NaN,6.0,144.0,5582.0,4965.0,650.0,1375.0,187.0,20.0,52.0,103.0,615.0,104.0,44.0,475.0,975.0,113.0,45.0,36.35,39.04,26.31,21.52,3.72,514900.0,127.0
634,2021,KT,황재균,3B,우투,우타,4.0,재자격,B,2020,33.0,134.0,600.0,541.0,108.0,169.0,35.0,5.0,5.0,21.0,97.0,11.0,6.0,47.0,98.0,12.0,4.0,5.03,-0.10,4.93,4.72,0.47,120000.0,고졸,NaN,NaN,NaN,3.0,144.0,5762.0,5047.0,813.0,1432.0,238.0,21.0,52.0,163.0,767.0,106.0,50.0,554.0,1097.0,104.0,45.0,21.71,15.80,11.90,27.89,2.10,584000.0,129.5
635,2022,KT,황재균,3B,우투,우타,4.0,재자격,B,2021,34.0,117.0,507.0,453.0,74.0,132.0,16.0,2.0,3.0,10.0,56.0,11.0,4.0,46.0,92.0,11.0,4.0,4.16,-0.12,4.04,2.41,0.41,80000.0,고졸,잔류,4.0,60.0,1.0,144.0,5627.0,4810.0,719.0,1276.0,219.0,11.0,58.0,106.0,673.0,112.0,46.0,645.0,1047.0,105.0,44.0,10.21,-7.11,0.42,21.86,1.33,575800.0,107.9
636,2023,KT,황재균,3B,우투,우타,NaN,FA 1년차,NaN,2022,35.0,141.0,581.0,519.0,59.0,136.0,25.0,3.0,5.0,10.0,64.0,6.0,3.0,53.0,99.0,17.0,2.0,-2.49,-0.25,-2.74,2.07,-0.26,40000.0,NaN,NaN,NaN,NaN,4.0,144.0,5547.0,4864.0,631.0,1237.0,192.0,19.0,49.0,119.0,588.0,89.0,34.0,519.0,1183.0,105.0,44.0,13.16,14.83,4.34,17.82,1.35,749000.0,97.1

In [201]:
df

,FA년도,구단명,선수명,포지션,투,타,인정년수,구분,FA등급,플레이년도,나이,게임수,타석수,타수,득점,안타,2루타,3루타,사구,홈런,타점,도루성공,도루실패,볼넷,삼진,병살타,희생플라이,평균대비수비득점기여,수비_포지션 RAA,전체수비 RAA,공격WAR,수비WAR,연봉,비고,잔류 여부,FA 계약 연수,FA 계약 총액,TEAM 순위,TEAM 게임수,TEAM 타석수,TEAM 타수,TEAM 득점,TEAM 안타,TEAM 2루타,TEAM 3루타,TEAM 사구,TEAM 홈런,TEAM 타점,TEAM 도루,TEAM 도루실패,TEAM 볼넷,TEAM 삼진,TEAM 병살타,TEAM 희생플라이,TEAM 평균대비수비득점기여,TEAM 수비_포지션 RAA,TEAM 전체수비 RAA,TEAM 공격WAR,TEAM 수비WAR,TEAM 연봉,wRC+
0,2011,롯데,강민호,C,우투,우타,9.0,신규,A,2010,25.0,117.0,465.0,410.0,66.0,125.0,19.0,1.0,8.0,23.0,72.0,2.0,7.0,42.0,65.0,16.0,5.0,1.74,9.48,11.21,3.67,0.35,NaN,고졸,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.4
1,2012,롯데,강민호,C,우투,우타,9.0,신규,A,2011,26.0,124.0,506.0,450.0,63.0,130.0,25.0,2.0,8.0,19.0,66.0,4.0,6.0,47.0,81.0,18.0,1.0,-1.00,11.72,10.73,3.90,0.23,NaN,고졸,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,130.3
2,2013,롯데,강민호,C,우투,우타,9.0,신규,A,2012,27.0,119.0,454.0,400.0,41.0,109.0,21.0,0.0,8.0,19.0,66.0,0.0,1.0,44.0,97.0,9.0,2.0,-1.68,9.16,7.48,3.76,0.65,NaN,고졸,NaN,NaN,NaN,4.0,133.0,5043.0,4481.0,509.0,1179.0,202.0,16.0,54.0,73.0,479.0,119.0,53.0,375.0,890.0,91.0,26.0,-41.49,13.36,-35.33,21.15,-3.15,289700.0,132.9
3,2014,롯데,강민호,C,우투,우타,9.0,신규,A,2013,28.0,105.0,405.0,327.0,48.0,77.0,13.0,0.0,11.0,11.0,57.0,4.0,1.0,60.0,87.0,5.0,6.0,7.18,8.93,16.11,1.75,1.81,NaN,고졸,잔류,4.0,75.0,5.0,128.0,4978.0,4289.0,556.0,1118.0,208.0,18.0,71.0,61.0,522.0,133.0,58.0,503.0,862.0,92.0,41.0,17.08,1.43,18.51,15.17,2.53,311900.0,99.2
4,2015,롯데,강민호,C,우투,우타,4.0,FA 1년차,A,2014,29.0,98.0,360.0,310.0,37.0,71.0,14.0,2.0,13.0,16.0,40.0,1.0,2.0,33.0,92.0,6.0,4.0,4.54,8.09,12.63,1.20,0.40,100000.0,고졸,NaN,NaN,NaN,7.0,128.0,5194.0,4487.0,716.0,1288.0,252.0,26.0,70.0,121.0,685.0,63.0,41.0,534.0,964.0,95.0,41.0,1.14,15.71,-6.57,16.88,0.10,510600.0,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,2019,KT,황재균,3B,우투,우타,4.0,재자격,B,2018,31.0,142.0,588.0,530.0,76.0,157.0,41.0,3.0,4.0,25.0,88.0,14.0,7.0,49.0,120.0,5.0,3.0,-0.96,-1.50,-2.46,3.54,-0.09,120000.0,고졸,NaN,NaN,NaN,9.0,144.0,5605.0,5026.0,757.0,1382.0,264.0,13.0,46.0,206.0,721.0,80.0,57.0,464.0,1109.0,103.0,26.0,-2.41,-7.35,-12.03,16.22,-0.35,607700.0,117.0
633,2020,KT,황재균,3B,우투,우타,4.0,재자격,B,2019,32.0,124.0,507.0,448.0,78.0,127.0,16.0,3.0,2.0,20.0,67.0,10.0,7.0,52.0,71.0,10.0,5.0,8.99,0.31,9.31,3.80,0.92,120000.0,고졸,NaN,NaN,NaN,6.0,144.0,5582.0,4965.0,650.0,1375.0,187.0,20.0,52.0,103.0,615.0,104.0,44.0,475.0,975.0,113.0,45.0,36.35,39.04,26.31,21.52,3.72,514900.0,127.0
634,2021,KT,황재균,3B,우투,우타,4.0,재자격,B,2020,33.0,134.0,600.0,541.0,108.0,169.0,35.0,5.0,5.0,21.0,97.0,11.0,6.0,47.0,98.0,12.0,4.0,5.03,-0.10,4.93,4.72,0.47,120000.0,고졸,NaN,NaN,NaN,3.0,144.0,5762.0,5047.0,813.0,1432.0,238.0,21.0,52.0,163.0,767.0,106.0,50.0,554.0,1097.0,104.0,45.0,21.71,15.80,11.90,27.89,2.10,584000.0,129.5
635,2022,KT,황재균,3B,우투,우타,4.0,재자격,B,2021,34.0,117.0,507.0,453.0,74.0,132.0,16.0,2.0,3.0,10.0,56.0,11.0,4.0,46.0,92.0,11.0,4.0,4.16,-0.12,4.04,2.41,0.41,80000.0,고졸,잔류,4.0,60.0,1.0,144.0,5627.0,4810.0,719.0,1276.0,219.0,11.0,58.0,106.0,673.0,112.0,46.0,645.0,1047.0,105.0,44.0,10.21,-7.11,0.42,21.86,1.33,575800.0,107.9
636,2023,KT,황재균,3B,우투,우타,NaN,FA 1년차,NaN,2022,35.0,141.0,581.0,519.0,59.0,136.0,25.0,3.0,5.0,10.0,64.0,6.0,3.0,53.0,99.0,17.0,2.0,-2.49,-0.25,-2.74,2.07,-0.26,40000.0,NaN,NaN,NaN,NaN,4.0,144.0,5547.0,4864.0,631.0,1237.0,192.0,19.0,49.0,119.0,588.0,89.0,34.0,519.0,1183.0,105.0,44.0,13.16,14.83,4.34,17.82,1.35,749000.0,97.1

In [203]:
df.to_csv('FA_야수데이터.csv', index = False)